### ISSUE TITLE
Tagging function stopped working because of plotting window

### ISSUE THREAD

**Issue by thoretz** [duderstadt-lab/mars-fx#1]
Ahoi Martians, 

While I was working with a molecular archive at one point I was unable to tag my molecules. Instead of adding the tag it was added as a title (see image). The weird letter combination coming after the word "reaction" comes from me punching different keys because no tag was added.

![Screenshot 2020-03-30 at 13 31 55](https://user-images.githubusercontent.com/61778269/77908100-241b2200-728b-11ea-9740-63591331b7f3.png)

My guess what happen: I changed the settings for the plot and I did not properly close the pop up window. If you don't do that it will write everything in the title box (could reproduce the error). Another thing I noticed I was unable to "scroll" through my molecules with the arrow keys (another indicator that something went wrong). 

So my workaround is basically to properly close the window and if you don't do that you can simply reload the archive or open the plot window again and close it. It is a minor thing but I want to let you know that this problem exist and in the first moment I was really confused.  

Thomas

**Comment by karlduderstadt** [comment]
Thank you @thoretz for reporting the unfortunately bug. I have looked into the issue in some depth and have a couple ideas about a solution.

Currently the popover window that comes up is not set to autoclose because when set to autoclose it is not possible to use the custom color pop-up. Basically, if you click the color selector and then the custom button, the whole thing immediately disappears because the popover looses focus and autohides. Therefore, autohide was set to false, but now I see this causes the problem that the popover can end up behind the main window if not properly closed. If it is behind the main window the test doesn't go to the main controls but instead goes to the popover...

I have explored adding custom listeners that respond to loss of focus type events to implement the autohide directly but only for the correct cases. Unfortunately, these solutions don't appear to work for a variety of reasons. 

So I think the best thing to do is get rid of the popover for entry of plot series and instead add a pane below the plot that comes up when you click the plot series button. This pane could then hide on a second click of the button. One advantage of this approach is that the same for plot series entry would also be full size.

I will add a new branch and attempt this work around and then get back to you. Thanks again for reporting this issue.

**Comment by karlduderstadt** [comment]
I implemented the move of the dataset option pane into a SplitPane under the charts and I think it addresses your issue. Now the dataset options buttons at the top control whether the options pane is visible and the chart you want to change the options for. I think this is also better since now it is possible to expand the window to see the whole PlotSeries table. 

There are still a few things to modify - like the spacing of the table columns and the table should also increase in size. I will add those now.

I added everything on a new branch for testing. Do you feel this addresses your problem? If so, I will add this into the master branch.

**Comment by karlduderstadt** [comment]
I think this is issue is resolved now, so I am closing it. @thoretz if you feel this doesn't solve your problem entirely we can reopen the issue.
