### ISSUE TITLE
Archive Molecule Filter can throw NullPointerException during saving

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-fx#12]
Hi @karlduderstadt,

I encountered a rather rare issue. When molecules are filtered by a tag and tags are manually removed, the filter doesn't update automatically. This seems to be a problem during saving: When the filter is on and a molecule without the filter tag is selected during saving, a NullPointerException occurs (and freezes the archive).
Maybe updating the filter right before saving would fix that issue?

<img width="930" alt="Bildschirmfoto 2020-05-23 um 15 07 51" src="https://user-images.githubusercontent.com/39280948/82731896-2d17f500-9d0a-11ea-8ed6-dffbfe90ccec.png">

**Comment by karlduderstadt** [comment]
Hi @mjosch,

Thanks for reporting this issue. As you correctly pointed out, the error occurs during the unlocking/refresh process. This process ensures that the GUI is up-to-date with the archive after processing. It attempts to restore the filter text and record selection, but in this case it seems to fail because the filter is not updated to reflect the change in tags that occurred during processing.

I made several commit to address this issue. I forgot to reference them, sorry. But I think the main commit that solved it was b3e2c5f. This commit ensure the filter list is updated before an attempt to restore the record selection. This address the issue.

There might still be a problem if you remove all tags from the filter list. I have added a check for this and if nothing remains in the list, the molecule pane will not update, so you shouldn't get an error. But once you change the filter and select a new record, the last selected record before processing will be saved. It is possible you could overwrite changes in that record. 

I am not sure about a workaround for this issue. Basically the molecule panel needs to unlock/refresh displaying nothing. Currently, I am not sure it would like to display nothing, but I will try and look into this. I suppose this is a rare case...

For now I am closing this issue.
