### ISSUE TITLE
Enable sideways scrolling on Mac

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#14]
At the moment only the vertical scroll bars respond to touchpad scrolling on a MacBook, and the horizontal scrollbars do not. It would be great to incorporate this feature.

**Comment by karlduderstadt** [comment]
I have been researching this issue and I am not really sure the solution. It is strange because vertical swipe does seem to work, but right and left swipe do not work. I think somehow it is just not enabled or coded for scroll panes in JavaFX, but JavaFX certainly has EventHandler for swiping in all directions, so it is possible.

I tried to detect and Handle swipe events on the TableView but for some reason they were not detected. There may have been a trivial issue here, but I am not sure. It is also possible that placing everything in the Fiji swing frame is blocking these swiping events, but the vertical swipe works...

This will need more investigation. If we can detect the events, we can add the code to have the scrollpane respond, but so far, I have not succeed in detecting them. I am afraid we might have to leave this for a future release. I will keep looking.

**Comment by karlduderstadt** [comment]
Despite my investigations, I haven't solved this. For me, sideways scrolling works perfectly fine in Fiji in other windows. These are all swing based. Mars-fx is based on javafx and to make it so the archive and table windows are seen by Fiji, they are swing windows with the javafx content inside. I think this might block the sideways scrolling so it never reaches the javafx content. I will test this by placing the javafx content back into a stage, which is a javafx window. But I am not sure how to solve this.

There are other issues with placing the javafx content into the swing window. For example, when you resize the window it looks horrible as the content updates. Also, the menus can't be closed by clicking a second time on them, you have yo click elsewhere outside of them. There two issue are fixed by going to a stage.

But for this to all work in Fiji, I think we should leave it inside of the swing window. Perhaps some of these issues have improved in more recent version of java, but I am not sure. I will leave this open for now until I test the behaviour in a stage window.

**Comment by karlduderstadt** [comment]
As discussed above this is a problem created by putting everything in a swing window. I am going to close this for now because using stages is not a good solution. There will be a migration to newer versions of java and other changes in Fiji. I think during the migration to the new java version and updating to the new javafx in the future would be a good time to revisit this issue and attempt to implement a solution.

In the regard, I am also not sure whether other JVMs might have different or better default behavior and already handle this issue. Perhaps the swing in the newest java version already resolves this issue. We will see as we overgrazed, but this will be more of a long-term project over the next 6 months.
