### ISSUE TITLE
Add 'Delete Positions' and 'Delete Regions' in tools menu

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#18]
At this moment there are the following tools: ‘Delete Molecules’ ‘Delete Molecule Tags’ ‘Delete Molecule Parameters’ and ‘Delete Segment Tables’. Wouldn’t it be nice to also have ‘Delete Regions’ and ‘Delete Positions’? 

=> You wrote that you implemented this but it is not visible in Rover.
* Maybe it is not included in the jars you gave me for testing?
* Maybe something needs to be refreshed f.e.?
<img width="266" alt="Screenshot 2020-09-10 at 15 22 02" src="https://user-images.githubusercontent.com/61824826/92735096-650a7d00-f379-11ea-929a-9813513a5a2e.png">

**Comment by karlduderstadt** [comment]
Yea, I agree would be good to have those! No I didn't have a chance to add them yet. Will require also indexing regions and positions globally so that the autocomplete works, so will take a little effort, but no so much. We should add it.

**Comment by karlduderstadt** [comment]
So MoleculeArchiveProperties keeps track of global name usage for tables, parameters. So first we need to add Region and position names. Then every time a new region or position is added we keep track to build the global set of unique region and position names. 

Should this be different for metadata and molecules? Usually, for the dialog I added dialogs that globally delete molecule properties. I figured there probably won't be too many metadata records, usually only one, and so those can be manually removed using the gui. Otherwise, it gets a bit complicated to keep tracking of regions and positions used for metadata vs molecules separately in the properties. This is all so we can do the autocompletion to suggest regions and positions that should be removed. 

I would go for just molecules and dialogs to remove those regions and positions globally. What do you think?

**Comment by karlduderstadt** [comment]
Delete Molecule Regions and Positions have been added to the menu and all required changes have been made in mars-core in commits duderstadt-lab/mars-core@7c540373d63663eabd0e7c614c26f24fa6b0f619 duderstadt-lab/mars-core@2472f390ae8a1f585923024d997eea653e1c763f duderstadt-lab/mars-core@3b1a778528951a4f94b5f09a334c624dfdc113d9 and duderstadt-lab/mars-fx@5661246b00f034840c362ae197a5b8de947f52d0. In initial tests Regions and Positions are removed as expected using the new dialogs.

**Comment by karlduderstadt** [comment]
I am closing for this for now. Everything here seems to work for me. We can reopen if problems arise.
