### ISSUE TITLE
Layout for smaller windows

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#27]
<img width="912" alt="Screenshot 2020-10-01 at 14 39 46" src="https://user-images.githubusercontent.com/61824826/94810295-22761680-03f4-11eb-882c-ed9e8ae080ad.png">

In smaller window settings (and in many cases also in the default size it shows up on my MacBook, the panel with molecule info like UUID, UID, tags etc does not show up correctly (see screenshot). Could you maybe fix this if it is not too difficult to do?

**Comment by karlduderstadt** [comment]
This the commit above, the molecule (and metadata) general properties layouts have been rebuilt and placed in a scroll pane so that a vertical scroll bar appears if the window become very small. A text area has been added for notes for clarity (based on in put from @BarbaraSafaric ).

<img width="948" alt="Screenshot 2020-10-12 at 12 43 11" src="https://user-images.githubusercontent.com/17951396/95737928-b82d6380-0c88-11eb-81b2-fdd436501ec3.png">

So I feel this issue is now addressed. Therefore, I am going to close it. Please feel free to reopen it whether you notice something else that needs addressing.
