### ISSUE TITLE
Remove molecule parameters bug (shows metadata parameters as well)

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#39]
I have encountered the following. The 'remove molecule parameters' option does what it intends to do, it only removes parameters from molecule records. When I type however, I do get suggestions for parameters in the metadata, I can select to remove those, but then it does not remove those from the metadata records. I think this behaviour is correct.
However, would it be possible to exclude those from the suggestions in the tool? It feels weird to get that as a suggestion when the tool does absolutely nothing with them once you select them.

Thank you!

**Comment by karlduderstadt** [comment]
Thanks for pointing out this issue. When records are stored in an archive and you call the methods setParameter, addTag, putRegion, putPosition defined in AbstractMarsRecord, the name/tag is also saved to the properties. Since this is all defined in AbstractMarsRecord, this happens for both Molecule and MarsMetadata records. 

The solution is to move this into the subclass AbstractMolecule, but not the subclass AbstractMarsMetadata. I will go ahead and do this, but I am now wondering, should we separately save all these properties for MarsMetadata records and then provide dialogs for removing that match those for molecule records?

**Comment by karlduderstadt** [comment]
This is addressed in mars-core with commit d3e43d3f633a01954be24cd4ed847c69f84dc6f6
