### ISSUE TITLE
Archive locked if you don't provide a segments table name to delete

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#58]
I stumbled upon the following. If I press 'Delete Segments Table' in the top left corner drop down menu of the archive, a dialog with a drop down menu appears with the names of the different segment tables I have in my archive. If you select any of those, then press enter or ok, the tool works fine. If you however fail to select one, then press enter by mistake, the archive is locked for eternity.

Would it be possible to add a line of code here checking if you selected anything, and if not, that you get a prompt with the info that you did not select anything instead of a locked archive?

<img width="303" alt="Screenshot 2022-04-06 at 13 52 35" src="https://user-images.githubusercontent.com/61824826/161968818-61538257-d057-4ea0-bcd0-e8f40128c760.png">

**Comment by karlduderstadt** [comment]
Yes ! Wow thanks for catching this, for sure we can check to hopefully avoid this issue in the future. I guess you can use a groovy script to just unlock it and continue working in the short term.

I have also been thinking about the mechanics of the status screen and whether there could be a cancel button or something that always unlocks it. But I guess it could be a bit tricky if it is a big long running process because it would then be stopped in the middle. Seems possible though.

**Comment by karlduderstadt** [comment]
I have the feeling there might be more issues like this in some of the other tool commands.
