### ISSUE TITLE
Disappearing widget windows upon rescaling

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#7]
Hi Karl,

When I am resizing the widgets (f.e. to get some more space for scripting) sometimes they disappear completely. They reappear when clicking on a widget in the toolbar again. Could you maybe take a look at what causes this?

Thank you :)

**Comment by karlduderstadt** [comment]
Thanks for reporting this issue! Yes, I have also seen this and this needs to be fixed. If you are expanding a widget next to another widget, sometimes it get so big it should go to a new line. If this happens the expansion continues and the widget is wider than the window. If a widget is wider than the window, it will not show up. Have you tried perhaps expanding the window to see if the missing widget reappears?

Keep in mind if you click the toolbar icons you will always create a new widget. You can have as many widgets as you like of all types. So the one the disappear is probably still there. Can you confirm?

I think the solution to this issue is to limit the expansion so it can't go beyond the window size. Also, if the widget would go to a new line it would be nice if the expansion stopped. This might be more difficult to implement.

We could also add a widget list somewhere so you can see all widgets you have created.

Thanks for reporting this issue! I will look into limiting the widget to the window size and stopping expansion if the widget moves to a new line.

**Comment by NadiaHuisjes** [comment]
I checked the things you suggest. Upon resizing the rover window again it reappears indeed. So I guess that was the problem indeed.
I think limiting it to the window size is a good idea!

**Comment by karlduderstadt** [comment]
After some more exploration, I have a partial solution. There are a couple commits finishing with 4bb1a38 that prevent widgets from expanding beyond the dashboard when resizing. Additionally, widgets will now shrinking to fit the width of the dashboard when resizing the window.

I forgot to reference the issue in all those commits, but it is the four or five before the number references above.

Unfortunately, there are still ways to causing the widgets to disappear when resizing the window. I do not have a complete solution for this at the moment. There is no way to gain access to the list of hidden nodes from the JFXMasonryPane. However, they will only disappear at certain fixed positions when resizing the window. Usually you would resize beyond these fixed positions to a smaller window size until it shows up again, so maybe it isn't even noticeable.

Please test and let me know if this addresses the problem and whether you have other suggestions.

(During testing I added a button to force all widgets to resize to fit, but then removed it because it didn't always cause them to reappear and wasn't really better than the automatic solution of just detecting when the window is narrower than the widgets and updated their widths.)

**Comment by karlduderstadt** [comment]
Hmm still seems to disappear on expansion if you try really hard. I will try and prevent expansion if the mouse is outside the window. This should also help..

**Comment by karlduderstadt** [comment]
Now as soon as the mouse leave the dashboard the widget resizing stops. Also, the max size is the closest size below the dashboard width in Cells. The JFXMasonryPane has a grid of 50x50 cells. This means you can't go all the way to the edge unless you are perfectly a multiple of this 50 in dashboard width. This seems to be the only way to ensure the widget never disappear when resizing their width. 

In rare cases it is still possible to make the widget disappear if you mean the window very small, but it virtually always comes back upon expansion. After lots of testing, I don't think there is anything else that can be done...

Please test and provide some feedback around whether the issue is addressed by cf94946

**Comment by NadiaHuisjes** [comment]
Hi Karl,
I did not have a disappearing widget so far again! Works much better now!
